#!/usr/bin/env bash
#
# One-time (and safely re-runnable) setup for Codespaces / Dev Containers.
#
# Brings a fresh checkout to the point where `npm run dev` actually serves the
# app: dependencies installed, .env written with a real secret, schema migrated.
set -euo pipefail

cd "$(dirname "$0")/.."

echo "==> Installing dependencies"
npm ci

# ---------------------------------------------------------------------------
# .env
#
# Both Next.js and the Prisma CLI must see these values. Next.js reads
# .env.local *and* .env, but the Prisma CLI only reads .env — so .env is the
# file that works for both, and the one this script writes.
# ---------------------------------------------------------------------------
if [ -f .env ]; then
  echo "==> .env already exists, leaving it alone"
else
  echo "==> Writing .env"

  # In a Codespace the browser reaches the app on a forwarded *.app.github.dev
  # host, not localhost. Pointing NEXTAUTH_URL/APP_URL at localhost there sends
  # every login redirect to an address the browser can't reach.
  if [ -n "${CODESPACE_NAME:-}" ]; then
    app_url="https://${CODESPACE_NAME}-3000.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
  else
    app_url="http://localhost:3000"
  fi
  echo "    app URL: ${app_url}"

  secret="$(openssl rand -base64 32)"

  cat > .env <<EOF
# Generated by .devcontainer/setup.sh — safe to edit.
DATABASE_URL="${DATABASE_URL:-postgresql://projectflow:projectflow@db:5432/projectflow}"

NEXTAUTH_SECRET=${secret}
NEXTAUTH_URL=${app_url}
APP_URL=${app_url}

# Seed account for \`npm run db:seed\` (optional).
AUTH_EMAIL=admin@projectflow.com
AUTH_PASSWORD=changeme-in-dev

# Optional integrations — see .env.example for the full list.
EOF
fi

echo "==> Applying database migrations"
npx prisma migrate deploy

echo "==> Generating Prisma client"
npx prisma generate

cat <<'EOF'

Setup complete.

  npm run dev     start the app on port 3000
  npm test        unit tests
  npm run db:seed create the seed account from AUTH_EMAIL / AUTH_PASSWORD

Open the forwarded port 3000 and register at /register.
If a page errors, check /api/health first — it reports database and schema state.
EOF
